# Generated by Django 3.1.7 on 2021-03-05 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mobile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_name', models.CharField(max_length=20, unique=True)),
                ('model_name', models.CharField(max_length=20)),
                ('price', models.IntegerField(default=1000)),
                ('specifications', models.TextField()),
                ('image', models.ImageField(upload_to='images')),
                ('quantity', models.IntegerField()),
            ],
        ),
    ]
