# Generated by Django 3.1.7 on 2021-03-20 07:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_mobile', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=20)),
                ('address', models.TextField()),
                ('phone', models.IntegerField()),
                ('status', models.CharField(default='Pending', max_length=50)),
                ('model_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_mobile.mobile')),
            ],
        ),
    ]
