# Generated by Django 3.1.7 on 2021-03-20 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_mobile', '0002_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='model_name',
            field=models.CharField(max_length=50),
        ),
    ]
