# Generated by Django 3.1.7 on 2021-03-27 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_mobile', '0005_auto_20210321_1412'),
    ]

    operations = [
        migrations.AddField(
            model_name='mobile',
            name='image_1',
            field=models.ImageField(default=0, upload_to='images'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mobile',
            name='image_2',
            field=models.ImageField(default=0, upload_to='images'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mobile',
            name='image_3',
            field=models.ImageField(default=0, upload_to='images'),
            preserve_default=False,
        ),
    ]
