# Generated by Django 3.1.7 on 2021-03-28 04:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_mobile', '0007_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='date',
            field=models.DateField(default=datetime.date(2021, 3, 28)),
        ),
    ]
