# Generated by Django 3.1.7 on 2021-03-28 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_mobile', '0008_order_date'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cart',
        ),
    ]
